### ISSUE TITLE
SPARQL VALUES bindings when nil should evaluate to an unbound var.

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#111]
e.g. in Query below if we bind `:collection-uri` to nil, we should remove `VALUES ?collection_uri`, if it's bound to a list of URIs we should get them interpolated into the VALUES clause.

As it stands in this case `?collection_uri` has no results, therefore nothing gets returned from the query.

```sparql
SELECT DISTINCT ?collection_type ?collection_type_plural_label ?collection_uri ?label ?description ?sortPriority WHERE {
  VALUES ?collection_uri {}

  ?collection_uri a ?collection_type .
  ?collection_type rdfs:subClassOf foi:FeatureCollection .
  ?collection_type foi:pluralDisplayName ?collection_type_plural_label .
  ?feat_within foi:memberOf ?collection_uri .
  ?feat_within foi:within ?resource_uri .
  ?collection_uri rdfs:label ?label .

  OPTIONAL {
    ?collection_uri dcterms:description ?description .
  }
  OPTIONAL {
    ?collection_uri ui:sortPriority ?sortPriority .
  }
} ORDER BY ASC(?sortPriority)
```

**Comment by scottlowe** [comment]
Working with the current Grafter implementation in client code, with two versions of the same query and different bindings, I have gotten around this issue by using `UNDEF` which works well, when I don't have a binding i.e.:

```sparql
SELECT (COUNT(DISTINCT ?member_uri) AS ?total) ?collection_uri WHERE {
  VALUES ?collection_uri { UNDEF }
  VALUES ?active {}

  ?member_uri foi:memberOf ?collection_uri .
  ?collection_type rdfs:subClassOf foi:FeatureCollection .
  ?member_uri foi:within ?resource_uri .
  ?member_uri foi:active ?active .
}
```

So extrapolating this idea, perhaps rather than removing the entire VALUES clause when we have a `nil` binding, we could translate the binding value of `nil` to UNDEF ? @RickMoynihan

**Comment by scottlowe** [comment]
Hah! Turns out that `nil` values in k/v pairs are already converted to `UNDEF`. So the real problem is that a `nil` binding isn't a k/v pair. I will look to see if I can fix the problem earlier and massage the `nil` binding into a MapEntry.

**Comment by RickMoynihan** [comment]
Ideally I think we should have the key ::sp/undef map to UNDEF and remove
the nil behaviour which might be better explicitly erroring.

Obviously this is a breaking change though I don't think anything relies on
it yet.

**Comment by scottlowe** [comment]
@RickMoynihan Okay. Well I've taken the alternative approach in the meantime, which seems to work well enough. Maybe I should submit 2 PRs and let you choose.

**Comment by scottlowe** [comment]
Offline discussion update: Will move to an explicit use of `::sp/undef` binding, and remove nil handling. Will throw exception if nil values discovered and suggest use of `::sp/undef` in the error message.
