### ISSUE TITLE
limits binding passed to query ignored 

### ISSUE THREAD

**Issue by jameslaneconkling** [Swirrl/grafter#128]
I'm having trouble overriding the `LIMIT` clause in my sparql query file.

Code is:
```clojure
(defn get-properties-for-type
  [type limit]
  (let [response (query "sparql/dbpedia/get-properties-for-type.sparql"
                        {:limits limit
                         :type (URI. type)}
                        (sparql-repo "http://dbpedia.org/sparql"))]
    (format-properties-response response)))
```

If I understand the source code correctly, this is because of the qualified keywords [here](https://github.com/Swirrl/grafter/blob/master/src/grafter/rdf/sparql.clj#L86-L92) (`::limits`).  I see that this was discussed [here](https://github.com/Swirrl/grafter/pull/76#issuecomment-236148774).  Perhaps I'm missing something (I'm new to the language): doesn't this mean that `limits` can't be specified in bindings outside of the `grafter/rdf/sparql.clj` file, i.e. in the implementing project?

Thanks for the help.

**Comment by jameslaneconkling** [comment]
ah OK, just learned you can import the necessary namespace when defining qualified keywords, e.g.

```javascript
(require '[grafter.rdf.sparql :as sparql])

{::sparql/limits some-limit}
```

and that the limit should be passed as a limit-variable/limit map.

so, this works:

```javascript
(defn get-properties-for-type
  [type limit]
  (let [response (query "sparql/dbpedia/get-properties-for-type.sparql"
                        {::sparql/limits {:limit limit }}
                         :type (URI. type)}
                        (sparql-repo "http://dbpedia.org/sparql"))]
    (format-properties-response response)))
```

However, though this works, I wonder if a qualified keyword is helpful here, given that there shouldn't be any other `:limit` keyword that could cause a namespace clash.  Is it even necessary?

Also, if helpful, I could submit a PR to clarify the function signature in the doc string.

**Comment by RickMoynihan** [comment]
Hi,

Sorry only just seen this issue - glad you sorted it out.  Yes, I'd take a PR to change this line in the doc string to include the fully qualified keyword in the docstring:

https://github.com/Swirrl/grafter/blob/a8875360be4a81cf5c22fb3665b547d375336d15/src/grafter/rdf/sparql.clj#L104

**Comment by RickMoynihan** [comment]
Sorry I should also clarify the rationale here:

1. It moves the `:limit` and `:offset` keys out of the domain of sparql variables.  i.e. `?grafter.rdf.sparql/limits` is not a valid sparql variable.  If we'd chosen the key `:limits` the query you are parameterising could bind that variable.
2. Namespaced keywords can be directly associated with specs.
3. Namespaced keywords give a clue as to where their definition belongs, i.e. you know this belongs to grafter not your sparql query or anything in your client code.
