### ISSUE TITLE
Is the purpose of this project to produce only RDF?

### ISSUE THREAD

**Issue by hansgru** [Swirrl/grafter#17]
Hi,

Is the main purpose of this project to product only RDF?

There doesn't seem to be many ETL frameworks for Clojure, and none that has a visual editor on the roadmap.

**Comment by RickMoynihan** [comment]
Hi,

Grafter has been built to aid our work transforming tabular data into linked data.  

So it consists of two parts, one to process tabular data; and the other to read/write and integrate with RDF.

These two parts are cleanly separated though; and the bulk of Grafter is really around the tabular processing part.  So yes, the aim is definitely to build a good ETL tool for tabular data too; though we don't yet have any SQL adapters, as our workloads so far have mainly had to extract and load from CSV/Excel.  Supporting SQL and other sources is definitely something I'd like to see though!

Currently Grafter distributes in a single package, but we're hoping to split the RDF dependencies out into separate projects.  We'd hoped this would have been done for 0.3.0, but we ran into some problems using lein-repack; which when resolved should let users use grafter without including RDF dependencies.

**Comment by hansgru** [comment]
>  so far have mainly had to extract and load from CSV/Excel.

Thank you for the details.

**Comment by RickMoynihan** [comment]
Its a pleasure.  

If you have any more questions - rather than feature requests or bug reports, please feel free to join our mailing list: 

https://groups.google.com/forum/?hl=en-GB#!forum/grafter-users
