### ISSUE TITLE
Rename s function to literal

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#24]
"Probably good reason for this, but my initial impression is that I'm not fond of the `s` function name.  I can see that you want a short name, and that it is used _everywhere_ so you want to reduce line noiseâ€¦  but given that it creates an RDF literal, why not call it `lit` or `literal`? Also makes executing a global `find` difficult and refactoring a pain, as well as other kinds of searches - google etc"

Strings in the `lang-or-uri` position should be treated as a URI for a datatype not a language tag.

**Comment by Robsteranium** [comment]
Isn't this only required to guard against strings being coerced to URIs? 

Will #25 mean that a string is not a `uri?` until it's cast explicitly? If yes we can't we just drop `s` altogether?

If we do need it and renamed it literal then what about non-string literals? Would `(literal 1.0)` still lead to "1.0" ^^xsd:decimal? Would it be confusing that you don't need to use `literal` in the case of typed literals?

This might be a concern best left until we think about error handling in a more general sense, but while we're talking about `s`: Both Nicholas and I are using a modded version akin to "maybe s" - i.e. s or nil if nil was passed. We then filter out statements with a nil (in any position) before writing.

On 16 April 2015 16:52:01 BST, Rick Moynihan <notifications@github.com> wrote:
>Probably good reason for this, but my initial impression is that I'm
>not fond of the `s` function name.  I can see that you want a short
>name, and that it is used _everywhere_ so you want to reduce line
>noiseâ€¦  but given that it creates an RDF literal, why not call it
>`lit` or `literal`? Also makes executing a global `find` difficult and
>refactoring a pain, as well as other kinds of searches - google etc
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Swirrl/grafter/issues/24

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RickMoynihan** [comment]
Hi @Robsteranium you raise some good points.

Firstly no `s` doesn't just guard against URI coercion, though that is its main use, it is also used to set language tags and support arbitrary typed literals via an additional URI parameter.

I propose that `(literal 1.0)` would just fall through so yes it would be the same as 1.0.  Raw strings would also default to the default string type probably sans language tag; but perhaps with a default.

The implementation of `literal` should actually make use of an `ILiteral` protocol allowing extension to arbitrary types; and we should obviously explicitly support all primitive types.

Regarding better errors - that work has been prioritised because it is needed for some other projects.  The is deadline for doing this is June 1st.  I have the details of this work broadly outlined in a gist, which I'll convert into a ticket soon; but I suspect this work will be done before the error work; though both might be released in the same version of Grafter (proposed 0.5.0).

**Comment by RickMoynihan** [comment]
About to start upgrading to sesame 2.8.x and some changes there about updating to RDF 1.1 have led to me unearthing this issue.  If you swap out sesame for the new 2.8.8 branch you get test failures because sesame's changed behaviours around language tags being required etc...

Anyway, that's an aside - I'm beginning to think we should split `s` into two functions - both `s` and `lit`.  

- `s` would create RDF strings either with or without a language tag.  e.g. `(s "Bonjour" :fr)` and `(s "hello")`
- `lit` would create literals e.g something like `(lit "2015-01-01" xsd-date-uri)` would be the long-hand way to create a date (we'd still have coercions defined).
- Coercions would finally change, so that raw java strings coerce into RDF strings without a language tag, and if you want a URI you set it explicitly.

We'd also remove `prefixer` and just use `URI`s/`URL`s and `grafter-url` for constructing URIs.
