### ISSUE TITLE
Demystify datasets

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#26]
The pipeline section in the Docs mentions Datasets a great deal and they seemed like something mysterious and complex to me initially until I dumped on to the REPL. It's probably worth mentioning that they are simply records with `:column-names` and `:rows`, e.g.:

**Comment by scottlowe** [comment]
Fixed in https://github.com/Swirrl/grafter-docs/pull/4

**Comment by RickMoynihan** [comment]
Merged on grafter-docs repo.
