### ISSUE TITLE
Apache Storm Support?

### ISSUE THREAD

**Issue by hansgru** [Swirrl/grafter#29]
Hi,

Are  there any plans to support Apache Storm?
https://storm.apache.org/

**Comment by RickMoynihan** [comment]
The short answer is no.

The longer answer is that we don't have a specific need for Storm support - and its not something I know a lot about, but having adapters to support reading and writing to other systems in general is something we'd be keen to see.

Regarding storm itself, my limited knowledge is that it is primarily made for data push scenarios, where as Grafter is currently built for data pull.  We are interested in eventually adding support for event streams to Grafter, but it will require significant changes, and isn't on our immediate roadmap.  

I'm hoping that Clojure 1.7's transducers might help us build this abstraction, and that when we do supporting systems like storm might be more likely.
