### ISSUE TITLE
Remove Triple records - we should just use Quad everywhere

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#33]
Having both Triple and Quad records causes problems with equality.

We should unify everything to be a Quad (which will still extend the Statement protocol).

If you want a Quad to be a Triple, you should just assign it a nil `:c`.

We may also want to add a predicate `triple?` function that tests if `(nil? (:c quad))`.

Any functions that return triples such as `triplify` should return Quads.

**Comment by akuckartz** [comment]
How was this resolved?

**Comment by RickMoynihan** [comment]
Sorry I forgot to push the changes.

It was resolved like this: 

https://github.com/Swirrl/grafter/compare/9ed77c13be1f8b051cedb57488cecdda644cd2d0...66ef07b87c24e5e15b4b682cf00f25fa60a4a1f8

There is still a `->Triple` function but thats just a shorthand for `(->Quad s p o nil)` - it will return a Quad type.
