### ISSUE TITLE
grafter.rdf.io/ISesameRDFConverter fails for common string values

### ISSUE THREAD

**Issue by lisp** [Swirrl/grafter#49]
short of delegating to a generic function which can be specialized per iri scheme, it would be most useful, were the conversion to make at least the most obvious distinctions, as in:

    (extend java.lang.String
     grafter.rdf.io/ISesameRDFConverter
     {:->sesame-rdf-type (fn [this] (if (re-matches #"(urn|http|https):.*" this) (URIImpl. this) (LiteralImpl. this)))
     })

**Comment by RickMoynihan** [comment]
Currently Grafter interprets strings as URI's.  There are tickets open to correct this, but if you want a String/literal you can use the `s` function to build one, and to rename `s` to `literal`.

If you want a URI/URL simply provide a java URI/URL/URIImpl or GrafterURL.

Happy to discuss further but I don't think matching strings that begin with a prefix is a robust solution.  If you want that behaviour you can choose to implement as part of your pipeline.

**Comment by lisp** [comment]
where does that leave one when importing data from an external source.
in the case in question, _everything_ is a literal.
do you propose all the data needs to go through an explicit intermediate step to reconstruct those values as literals?

**Comment by RickMoynihan** [comment]
Apologies if I have the wrong end of the stick, but Grafters query function should really return you the RDF types as they were serialised into RDF.  

So if you have URI's that are stored as Strings, yes I'd expect to get strings back out, regardless of whether they look like URI's.  So I'd suggest something like this (untested):

````clojure
(defn ->uri [s]
  (java.net.URI. (str s)))

(with-open [conn (->connection repo)]
   (doseq [res (query conn "SELECT * WHERE { ?s ?p ?o .} LIMIT 10")]
      (->> res
             (map (comp ->uri #(get "o"))))
````

You could of course patch over the low level protocol definition, but you'll change the behaviour globally.  

Related to this you might also notice that the types you get back from query aren't yet round-tripped into Clojures types.  This is a planned change (see #40).

**Comment by lisp** [comment]
the use case, as noted above, is is not the data flow from the store, but "when importing data from an external source" into the store. it ought to be possible to point a pipeline at a source and have it to the right thing and need to interpose reconstruction if something in the content requires logic beyond that of type recognition only.
the issue concerns a change - the converter cited above,  which i understood to have placed at the most purposeful place on the data path _into_ the store to recognize whether a datum is intended to be stored as a literal or as an iri.

**Comment by RickMoynihan** [comment]
Sorry... My mistake I should've read your code sample more closely! 

Can you tell me specifically what you're actually trying to achieve though?  It's quite hard to guess what your use case is?  

Those protocols are used by quite a bit of Grafter already for marshaling data to/from Clojure and sesame RDF types.  Specifically that particular protocol function is intended to support `add`/`add-statement` on the `ITripleWriteable` protocol.

You can always override the implementation of the protocol yourself, in your own library - stomping on Grafters own String implementation.  This might work for you if you want that behaviour everywhere `add`/`add-statement`/`->sesame-rdf-type` are called.

Again the safest way is probably to extend things at the higher level, e.g. implement ITripleWriteable on your own type, then delegate to the un-modified `->sesame-rdf-type` to get its existing type conversion and finally special case the string conversion in your `add` implementation with an `(let [sesobj (if (instance StringLiteral sesobj) (convert-if-looks-like-uri sesobj) sesobj)`.

Would that work?

**Comment by lisp** [comment]
you did notice the arff support.

our use case is not that of exposing rdf data externally through grafter but of using grafter to mediate access to incanter and to weka.
in this situation, my sense is that the restriction to string and integer cell content should prevail.
at least for a first order implementation.

perhaps this indicate that there should be some variation among dataset classes, to distinguish those with strict content from those with rdf term content.
as a naive user, rdf term content was not expected.
