### ISSUE TITLE
Error loading on OSX 10.10

### ISSUE THREAD

**Issue by pmackay** [Swirrl/grafter#52]
I have `java version "1.6.0_65"` installed on OS X and when I run `lein repl` in the test project I get the error below. Just wondering if you have come across this and know a quick fix? 

```
...
Retrieving slingshot/slingshot/0.10.3/slingshot-0.10.3.jar from clojars
Retrieving net/mikera/core.matrix/0.7.2/core.matrix-0.7.2.jar from clojars
Retrieving com/novemberain/pantomime/2.4.0/pantomime-2.4.0.jar from clojars
Could not find artifact com.sun:tools:jar:1.5 at specified path /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../lib/tools.jar
```

I dont get this from testing with a regular clojure project, so I assume its related to one of the dependencies of grafter.

**Comment by RickMoynihan** [comment]
I haven't seen this myself, but believe its a problem with JDK 6 on some
versions of OS X.

You could try this:

http://dbknickerbocker.blogspot.co.uk/2013/04/simple-fix-to-missing-toolsjar-in-jdk.html

Or try installing a more recent JDK (e.g. JDK 8).

R.

**Comment by pmackay** [comment]
Thanks, a more recent JDK has solved it.
