### ISSUE TITLE
Allow SPARQL bindings to be programatically set

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#75]
It's useful to be able to set bindings ontop of SPARQL queries, allowing an underlying query to be used as a kind of template.

JENA does something like this, and [yesparql](https://github.com/joelkuiper/yesparql) exposes it.  Unfortunately we use sesame/RDF4j, so can't use yesparql.

However sesame/RDF4j do support something similar by setting bindings!  See here for a [branch implementing this with grafter](https://github.com/Swirrl/grafter/blob/rick/better-sparql/src/rdf-repository/grafter/rdf/sparql.clj).

Unfortunately this relies on Sesame/RDF4j doing this, and Sesame doesn't have some features we'd like:
- Being able to set `LIMIT` and `OFFSET`s (not supported in Sesame because `LIMIT`/`OFFSET` according to the SPARQL grammar can't take a variable; and therefore they can't be provided as "bindings"
- VALUES being able to provide values would be good too... e.g. providing `[1 2 3 4]` to `?foo` might result in:

``` sparql
SELECT * WHERE { 
   VALUES ?foo {}
}   
```

``` sparql
SELECT * WHERE { 
   VALUES ?foo { 1 2 3 4 }
}   
```

For background also see this discussion I brought up on the [RDF4j mailing list](https://groups.google.com/forum/#!topic/rdf4j-users/Z1jGWFaMgsA), and also [this discussion about binding semantics](https://groups.google.com/d/msg/rdf4j-devel/Di_ZLtTVuZA/W7luv0sNsaEJ) on the RDF4j mailing list

Because of these limitations it seems we might need to implement these features as a pre-process step, ideally using a proper SPARQL parser.   We might be able to implement such a parser relatively easily ourselves in clojure using [Instaparse](https://github.com/Engelberg/instaparse) and running it over the [SPARQL 1.1 EBNF grammar](https://www.w3.org/TR/sparql11-query/#grammar), after processing the string with our parser we'd then want to unparse it back into a string and submit it to RDF4j/Sesame.

In the interim we could probably add this by using a dirty regex to replace `LIMIT ?varname`/`OFFSET ?othervarname` with values supplied in our bindings map.

**Comment by scottlowe** [comment]
There is a naive VALUES implementation here:

https://github.com/Swirrl/dclg-iu-dashboard/blob/95d0dd3f4dbfced70fcc7d7d9053ddf98c52a7df/src/dashboard/db/core.clj#L47-L91

It doesn't currently look for and replace empty braces following binding vars in the source file.

**Comment by RickMoynihan** [comment]
Basic support incorporated in 0.8.4+ release.
