### ISSUE TITLE
RDF 2 RDF transformation.

### ISSUE THREAD

**Issue by samuraraujo** [Swirrl/grafter#99]
Grafter seems quite powerful, I would like to use it to transform RDF to RDF.

How easy would be to write an adapter to transform RDF to RDF using grafter?

**Comment by RickMoynihan** [comment]
It has features to do this already such as: 

- Wrappers over the RDF repositories within sesame e.g. `grafter.rdf.repository/sparql-repo`
- [grafter.rdf.sparql](http://api.grafter.org/docs/master/grafter.rdf.sparql.html) for issuing SPARQL queries.  In particular you can use `CONSTRUCT` queries to emit a sequence of RDF triples.
- ... this stream of RDF triples can be modified via clojure's sequence apis, e.g. `map`, `filter`, `remove`, or using clojure sets or maps for manipulating the data further.
- You can also load triples into repositories `(grafter.rdf/add repo triple-seq)` or serialise them to files `(grafter.rdf/add (grafter.rdf.io/rdf-serialiser "/tmp/foo.nt" :format :nt) triples-seq)`

What specific features do you want?
